title: 培训申请
modelClass: Samubra\Train\Models\Apply
list: $/samubra/train/models/apply/columns.yaml
filter: config_filter.yaml
recordUrl: 'samubra/train/applies/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
