title: 报名申请
modelClass: Samubra\Train\Models\Apply
list: $/samubra/train/models/apply/columns.yaml
recordUrl: 'samubra/train/applies/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
