plugin:
    name: 'samubra.train::lang.plugin.name'
    description: 'samubra.train::lang.plugin.description'
    author: samubra
    icon: oc-icon-adjust
    homepage: 'http://tiikoo.cn'
permissions:
    lookup.manage:
        tab: 'samubra.train::lang.lookup.manage'
        label: 'samubra.train::lang.lookup.manage'
    category.manage:
        tab: 'samubra.train::lang.category.manage'
        label: 'samubra.train::lang.category.manage'
    plan.manage:
        tab: 'samubra.train::lang.plan.manage'
        label: 'samubra.train::lang.plan.manage'
    teacher.manage:
        tab: 'samubra.train::lang.teacher.manage'
        label: 'samubra.train::lang.teacher.manage'
    course.manage:
        tab: 'samubra.train::lang.course.manage'
        label: 'samubra.train::lang.course.manage'
    record.manage:
        tab: 'samubra.train::lang.record.manage'
        label: 'samubra.train::lang.record.manage'
navigation:
    plan-menu-item:
        label: 培训管理
        url: samubra/train/plans
        icon: icon-building
        permissions:
            - plan.manage
        sideMenu:
            plan-item:
                label: 'samubra.train::lang.plan.manage'
                url: samubra/train/plans
                icon: icon-space-shuttle
                permissions:
                    - plan.manage
            course-item:
                label: 'samubra.train::lang.course.manage'
                url: samubra/train/courses
                icon: icon-stack-overflow
                permissions:
                    - course.manage
            record-item:
                label: 'samubra.train::lang.record.manage'
                url: samubra/train/records
                icon: icon-credit-card
                permissions:
                    - record.manage
            record-import-item:
                label: 导入操作证
                url: samubra/train/records/import
                icon: icon-cloud-upload
                permissions:
                    - record.manage
    lookup-menu-item:
        label: 基础数据
        url: samubra/train/lookups
        icon: icon-simplybuilt
        permissions:
            - lookup.manage
        sideMenu:
            lookup-item:
                label: 'samubra.train::lang.lookup.manage'
                url: samubra/train/lookups
                icon: icon-simplybuilt
                permissions:
                    - lookup.manage
            teacher-item:
                label: 'samubra.train::lang.teacher.manage'
                url: samubra/train/teachers
                icon: icon-user-secret
                permissions:
                    - teacher.manage
            category-item:
                label: 'samubra.train::lang.category.manage'
                url: samubra/train/categories
                icon: icon-sitemap
                permissions:
                    - category.manage
