# ===================================
#  Relation Behavior Config
# ===================================

applies:
    label: 培训记录
    view:
        list: $/samubra/train/models/apply/columns_for_record.yaml
    readOnly: true
