title: 操作证列表
modelClass: Samubra\Train\Models\Record
filter: config_filter.yaml
list: $/samubra/train/models/record/columns.yaml
recordUrl: 'samubra/train/records/preview/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
export:
    useList: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
