title: 数据列表
modelClass: Samubra\Train\Models\Lookup
list: $/samubra/train/models/lookup/columns.yaml
recordUrl: 'samubra/train/lookups/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: '30'
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
